contextId=contextid
contextData=contextdata
contextIdType=contextidtype
rootOrgId=rootorgid
profileDetails=profiledetails
contextid=contextId
contextidtype=contextIdType
contextdata=contextData
isarchived=isArchived
planid=planId
orgscope=orgScope
contentlist=contentList
contenttype=contentType
draftdata=draftData
enddate=endDate
isapar=isApar
orgidlist=orgIdList
createat=createdAt
createdby=createdBy
updatedat=updatedAt
updatedby=updatedBy
firstname=firstName
userid=userId
orgid=orgId
assignmenttype=assignmentType
assignmenttypeinfo=assignmentTypeInfo
rootorgid=rootOrgId
additionalattributes=additionalAttributes